name: Playwright Tests

on:
  deployment_status:
jobs:
  run-e2es:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pnpm install && npx playwright install --with-deps
        working-directory: ./apps/store
      - name: Run tests
        run: npx playwright test
        working-directory: ./apps/store
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}